#!/bin/sh

# exit if command fails
set -e
# sane behaviour for cd
unset CDPATH
# set IFS to SP HT LF.
IFS=' 	
'

usage () {
  cat << EOF
usage: $(basename "$0") [OPTION]... FILE

options:
  -h    display this help and exit
EOF
}

while getopts "h" opt; do
  case "$opt" in
    h)
      usage >&1
      exit 0
      ;;
    \?)
      usage >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

file="$1"

if ! which pygmentize >/dev/null 2>&1; then
  printf "pygmentize not found.\neasy_install it.\n" >&2
  exit 127
fi

if [ -z "$file" ]; then
  file=/dev/stdin
elif [ ! -e "$1" ]; then
  printf "%s: %s: No such file or directory" "$(basename "$0")" "$file" >&2
  exit 2
elif [ -d "$file" ]; then
  printf "%s: %s: Is a directory" "$(basename "$0")" "$file" >&2
  exit 2
fi

pygmentize -f terminal -g $file

# vim: ft=sh ts=2 sts=2 sw=2 et:
