#!/usr/bin/env bash

if ! which weechat-curses >/dev/null 2>&1; then
    printf "weechat-curses not found\n" >&2
    exit 1
fi

tmux_session_name="chat"
tmux_window_name="weechat"
weechat_command=$(which weechat-curses)

if tmux has-session -t "$tmux_session_name" &>/dev/null ; then
    tmux attach-session -t $tmux_session_name \; select-window -t $tmux_window_name
else
    tmux new-session -n $tmux_window_name -s $tmux_session_name $weechat_command
fi

# vim: ft=sh:
