#!/bin/sh

# exit if command fails
set -e
# sane behaviour for cd
unset CDPATH
# set IFS to SP HT LF.
IFS=' 	
'

usage () {
  cat << EOF
usage: $(basename "$0") [OPTIONS]... <SIDES | POSSIBILITIES...>

Roll a dice.
Either with SIDES sides (1..n) or with the given possibilities (> 1)

options:
  -h    display this help and exit.
EOF
}

while getopts "h" opt; do
  case "$opt" in
    h)
      usage >&1
      exit 0
      ;;
    \?)
      usage >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

if [ $# -eq 0 ]; then
  printf >&2 "No arguments given.\n\n"
  usage >&2
  exit 2
fi

rand="/dev/random"
if [ -r "/dev/urandom" ]; then
  rand="/dev/urandom"
fi
rand=$(od -An -N4 -i "$rand" |tr -d "[:space:]-")

if [ $# -eq 1 ]; then
  if [ -z "$(echo "$1" |tr -d "[:digit:]")" ]; then
    printf "%d\n" $(( 1 + (rand % $1) ))
    exit 0
  fi
fi

rand=$(( 1 + (rand % $#) ))
eval rand="\$$rand"
printf "%s\n" "$rand"

# vim: ft=sh ts=2 sts=2 sw=2 et:
