#!/bin/sh

set -eu
unset CDPATH
IFS=' 	
'

usage () {
  cat << EOF
usage: $(basename "$0") [OPTIONS]... <SIDES | POSSIBILITIES...>

Roll a dice.
Either with SIDES sides (1..n) or with the given possibilities (> 1)

options:
  -h    display this help and exit.
EOF
}

while getopts "h" opt; do
  case "$opt" in
    h)  usage >&1 ; exit 0 ;;
    \?) usage >&2 ; exit 1 ;;
  esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
  printf >&2 "%s: No arguments given.\n\n" "$(basename "$0")"
  usage >&2
  exit 2
fi

if [ $# -eq 1 ]; then
  seq 1 "$1" |shuf |sed '1q'
else
  for p in "$@"; do
    printf "%s\n" "$p"
  done |shuf |sed '1q'
fi

# vim: ft=sh ts=2 sts=2 sw=2 et:
