#!/usr/bin/env bash

# sane behaviour for cd
unset CDPATH
# set IFS to SP HT LF.
IFS=' 	
'

if [ ! -d ".git" ]; then
  printf "not the root of a git repository\n" >&2
  exit 1
fi

cur=$(pwd)
printf "found %s submodules\n" "$(git submodule status | wc -l)"

while read submodule; do
  s=(${submodule// / })
  if [ -n "${s[1]}" ]; then
    cd "${s[1]}"

    printf "\e[0;34mchecking '\e[0;33m%s\e[034m'\e[0m\n" "${s[1]}"
    git checkout master
    git pull

    cd "$cur"
  fi
done <<< "$(git submodule status)"

# vim: ft=sh ts=2 sts=2 sw=2 et:
