#!/usr/bin/env bash

command -v mutt >/dev/null 2>&1 || { echo >&2 "weechat-curses not found"; exit 1; }

tmux_session_name="mail"
tmux_window_name="mutt"
mutt_command=`which mutt`

if tmux has-session -t "$tmux_session_name" &>/dev/null ; then
    tmux attach-session -t $tmux_session_name \; new-window -t $tmux_window_name
else
    tmux new-session -n $tmux_window_name -s $tmux_session_name $mutt_command
fi

# vim: ft=sh:
