#!/usr/bin/env sh

usage () {
    echo "Usage: $(basename "$0") [OPTIONS]... FILES...

Creates a new PDF by merging the given PDF files into a single one.

  -o <name>   name of the new PDF, defaults to 'merged.pdf'
  -h          display this help and exit"
}

outname="merged.pdf"

while getopts "o:h" opt; do
    case "$opt" in
        o)
            outname="$OPTARG"
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
            usage
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="$outname" "$@"
exit $?
