#!/usr/bin/env sh
#
# nautilus
#

args=("$@")
file="$HOME"

if [ "${#args[@]}" -ne 0 ]; then
	file=${args[-1]}
fi

if [[ -x /usr/bin/nautilus ]]; then
    exec nautilus "$@"
elif [[ -x /usr/bin/pcmanfm ]]; then
    exec pcmanfm --new-win "$@"
elif [[ -x /usr/bin/i3-sensible-terminal ]]; then
    if [[ -x /usr/bin/ranger ]]; then
        exec i3-sensible-terminal -e ranger "$file"
    elif [[ -x /usr/bin/mc ]]; then
        exec i3-sensible-terminal -e mc "$file"
    fi
else
    echo "No applicable program found"
    exit 1
fi

