#!/usr/bin/env sh
#
# nautilus
#

args=("$@")
file="$HOME"

if [ "${#args[@]}" -ne 0 ]; then
	file=${args[-1]}
fi

if [[ -x /usr/bin/nautilus ]]; then
    exec nautilus "$@"
elif [ $(command -v pcmanfm) ]]; then
    exec pcmanfm --new-win "$@"
elif [ $(command -v thunar) ]; then
    exec thunar "$file"
elif [ $(command -v i3-sensible-terminal) ]; then
    if [ $(command -v ranger) ]; then
        exec i3-sensible-terminal -e ranger "$file"
    elif [ $(command -v mc) ]; then
        exec i3-sensible-terminal -e mc "$file"
    fi
else
    echo "No applicable program found"
    exit 1
fi

