#!/bin/sh
#
# Prezi key bindings for the Logitech R400 Wireless Presenter
#

prezi_start() {
  printf "Bound keys for prezi presentation\n"
  printf "112 = Left, 117 = Right"
  xmodmap -e "keycode 112 = Left" -e "keycode 117 = Right"
}

prezi_stop() {
  printf "Bound keys back to normal"
  printf "112 = Prior, 117 = Next"
  xmodmap -e "keycode 112 = Prior" -e "keycode 117 = Next"
}

if [ "$1" = "on" -o "$1" = "start" ]; then
  prezi_start
elif [ "$1" = "off" -o "$1" = "stop" ]; then
  prezi_stop
else
  key112=$(xmodmap -pk | grep 112 | grep Prior)
  if [ "z$key112" = "z" ]; then
    prezi_stop
  else
    prezi_start
  fi
fi

# vim: ft=sh ts=2 sts=2 sw=2 et:
