#!/usr/bin/env sh

usage ()
{
  echo "Usage: $(basename "$0") [OPTIONS]...

Prints the public IP-Address.

Options:
  -v    verbose output
  -h    display this help and exit"
}

verbose=0

while getopts "vh" opt; do
  case "$opt" in
    h)
      usage
      exit 0
      ;;
    v)
      verbose=1
      ;;
    \?)
      usage
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

if [ $(command -v dig) ]; then
  [ "$verbose" -eq 1 ] && set -o xtrace
  dig +short @resolver1.opendns.com myip.opendns.com
elif [ $(command -v curl) ]; then
  [ "$verbose" -eq 1 ] && set -o xtrace
  curl -s "http://checkip.dyndns.org" | grep --color=never -o "[[:digit:].]\+"
elif [ $(command -v wget) ]; then
  [ "$verbose" -eq 1 ] && set -o xtrace
  wget -q -O- "http://checkip.dyndns.org" | grep --color=never -o "[[:digit:].]\+"
fi

# vim: ft=sh ts=2 sts=2 sw=2 et:
