#!/bin/sh

# exit if command fails
set -e
# sane behaviour for cd
unset CDPATH
# set IFS to SP HT LF.
IFS=' 	
'

if test "$(id -u)" -ne 0; then
  printf "not running as root.\n" >&2
fi

if which pacman >/dev/null 2>&1; then
  pacman -Syu
elif which apt-get >/dev/null 2>&1; then
  apt-get update && apt-get upgrade
fi

# vim: ft=sh ts=2 sts=2 sw=2 et:
