#!/bin/sh

# exit if command fails
set -e
# set IFS to SP HT LF.
IFS=' 	
'

usage () {
  cat << EOF
usage: $(basename "$0") [OPTIONS]... FILE

Reads FILE (which must have the format of /proc/uptime)
and displays the uptime in a human readable way.

If FILE is '-', STDIN is used.
By default, /proc/uptime is used as FILE.

options:
  -h          display this help and exit
EOF
}

while getopts "h" opt; do
  case "$opt" in
    h) usage >&1 ; exit 0 ;;
    \?) usage >&2 ; exit 1 ;;
  esac
done

shift $((OPTIND-1))

awk '
BEGIN {
  FS=" "
}
NR == 1 {
  secs = int($1)
  if (secs < 60) {
    printf("%02d Sec\n", secs );
  } else if (secs < (60 * 60)) {
    printf("%02d Min\n", (secs / 60));
  } else {
    mins = int(secs / 60 % 60)
    hours = int(secs / 60 / 60 % 24)
    days = int(secs / 60 / 60 / 24)
    if (days > 0) {
      printf("%d %s %02d:%02d\n", days, (days > 1) ? "Days" : "day", hours, mins)
    } else {
      printf("%02d:%02d\n", hours, mins)
    }
  }
  exit
}
' "${1:-/proc/uptime}"

# vim: ft=sh ts=2 sts=2 sw=2 et:
